# Generated by Django 2.2.5 on 2019-09-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqdn_name_Nuc', models.CharField(blank='', max_length=255)),
                ('mac_addr_Nuc', models.CharField(max_length=18)),
                ('enables_Nuc', models.BooleanField(default=False)),
                ('ip_addr_Nuc', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfNuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=12)),
                ('DisplayType', models.CharField(max_length=32)),
            ],
        ),
    ]
