# Generated by Django 2.2.5 on 2019-09-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nucs', '0002_auto_20190903_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nucs',
            old_name='enables_Nuc',
            new_name='enables_nuc',
        ),
        migrations.RenameField(
            model_name='nucs',
            old_name='fqdn_name_Nuc',
            new_name='fqdn_name_nuc',
        ),
        migrations.RenameField(
            model_name='nucs',
            old_name='ip_addr_Nuc',
            new_name='ip_addr_nuc',
        ),
        migrations.RenameField(
            model_name='nucs',
            old_name='mac_addr_Nuc',
            new_name='mac_addr_nuc',
        ),
    ]
