# Generated by Django 2.2.5 on 2019-09-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nucs', '0003_auto_20190903_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='FFC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='', max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='nucs',
            options={'ordering': ('fqdn_name_nuc',)},
        ),
    ]
