# Generated by Django 2.2.5 on 2019-09-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nucs', '0004_auto_20190920_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='ffc',
            name='suff',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ffc',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
