# Generated by Django 2.2.5 on 2019-09-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nucs', '0005_auto_20190920_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='ffc',
            name='domain',
            field=models.CharField(default='.market.yandex.net', max_length=256),
        ),
    ]
