# Generated by Django 2.2.5 on 2019-09-20 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nucs', '0008_auto_20190920_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ffc',
            name='suff',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='nucs',
            name='ffc_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nucs.FFC', to_field='suff'),
        ),
    ]
