# Generated by Django 2.2.5 on 2019-09-20 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nucs', '0014_auto_20190920_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ffc',
            name='suff',
            field=models.CharField(blank='', default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='nucs',
            name='ffc_code',
            field=models.ForeignKey(blank='', default='', on_delete=django.db.models.deletion.CASCADE, to='Nucs.FFC'),
        ),
    ]
