# Generated by Django 2.2.5 on 2019-09-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nucs', '0015_auto_20190920_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ffc',
            name='suff',
            field=models.CharField(max_length=6),
        ),
    ]
