# Generated by Django 2.2.5 on 2019-09-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nucs', '0017_auto_20190920_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nucs',
            name='ffc_code',
        ),
    ]
