# Generated by Django 2.2.5 on 2019-09-20 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nucs', '0022_auto_20190920_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ffc',
            name='domain',
            field=models.CharField(default='.market.yandex.net', max_length=256, verbose_name='Домен'),
        ),
        migrations.AlterField(
            model_name='ffc',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='Наименование ФФЦ'),
        ),
        migrations.AlterField(
            model_name='ffc',
            name='suff',
            field=models.CharField(max_length=6, unique=True, verbose_name='Суффикс'),
        ),
        migrations.AlterField(
            model_name='nucs',
            name='ffc_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nucs.FFC'),
        ),
        migrations.AlterField(
            model_name='nucs',
            name='fqdn_name_nuc',
            field=models.CharField(blank='', max_length=255, verbose_name='Имя NUC'),
        ),
        migrations.AlterField(
            model_name='nucs',
            name='ip_addr_nuc',
            field=models.CharField(max_length=36, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='nucs',
            name='mac_addr_nuc',
            field=models.CharField(max_length=18, verbose_name='mac адрес'),
        ),
    ]
